version: '3.4'

services:
  oracle:
#    image: xrdj6c/oracle-11g-xe
    image: howarddeiner/oracle-11g-ee
    container_name: oracle
    networks:
      - backend
    ports:
      - "1521:1521"
      - "8081:8080"
    restart: always
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    healthcheck:
      test: ["CMD", "curl", "-s", "-S", "-f", "localhost:8081"]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 1m
networks:
  backend: