-- SET ECHO ON

/*
DROP TYPE INCV.ACTIVITYCCCURENCELIST_OBJ;
*/

CREATE OR REPLACE TYPE INCV.ACTIVITYCCCURENCELIST_OBJ
    FORCE
AS
  OBJECT
  (
    RewardId                       NUMBER(38),
    Supplierid                     NUMBER(38),
    Activityid                     NUMBER(38),
    Rewardstatus                   VARCHAR2(50),
    Recordstatus                   VARCHAR2(50),
    Activitystatus                 VARCHAR2(50),
    Activityoccurstatus            VARCHAR2(50),
    Activityoccurrencedt           TIMESTAMP,
    Isopen                         VARCHAR2(1),
    Ispresent                      VARCHAR2(1),
    Isapplicable                   VARCHAR2(1),
    Param1                         VARCHAR2(255),
    Param2                         VARCHAR2(255),
    Param3                         VARCHAR2(255),
    Rewardcompletiondate           TIMESTAMP(6),
    Activitycompletiondt           TIMESTAMP(6),
    OverriddenyInd                 VARCHAR2(1),
    Mbrincentivestatusoverrideskey NUMBER(38),
    Invalidind                     VARCHAR2(1),
    Activitystartdt                TIMESTAMP,
    Activityenddt                  TIMESTAMP,
    Rewardstartdt                  TIMESTAMP,
    Rewardenddt                    TIMESTAMP,
    Justificationtxt               CLOB,
	MEMBERACTIVITYOCCURVALUE       MEMBERACTIVITYOCCURVAL_TAB
  );


/*
DROP TYPE INCV.ACTIVITYCCCURENCELIST_TAB;
*/

CREATE OR REPLACE TYPE INCV.ACTIVITYCCCURENCELIST_TAB
IS
  TABLE OF ACTIVITYCCCURENCELIST_OBJ;


/*
DROP TYPE INCV.ACTIVITY_CONFIGURATION_OBJ;
*/

CREATE OR REPLACE TYPE INCV.ACTIVITY_CONFIGURATION_OBJ FORCE as object (
	ACTIVITYDESC					VARCHAR2(200),
	ACTIVITYTITLETXT				VARCHAR2(200),
	GENDER						    VARCHAR2(1),
	ACTIVITYTYPEMNEMONIC			VARCHAR2(50),
	STARTDATE						DATE,
	ENDDATE							DATE,
	NUMBEROFOCCURANCE				NUMBER,
	MINREQUIREDOCCURRENCE			NUMBER,
	SORTORDERNBR					NUMBER,
	REQUIREDYNIND                   VARCHAR2(1),
	ALTERNATIVE                     VARCHAR2(1),
	DISPLAYORDER                    NUMBER,
	ISREQUIREDFORGROUP              VARCHAR2(1),
	RELATIONTYPE                    VARCHAR2(50),
	DEPENDENTACTIVITYCOUNT          NUMBER,
	INCENTIVESVALUES                INCV.INCENTIVE_GOAL_TAB,
	ACTIVITYATTRIBUTEARRAY          INCV.ATTRIBUTE_CONFIGURATION_TAB,
	CHILDACTIVITYARRAY              INCV.CHILD_ACTIVITY_CONFIG_TAB,
	ACTIVITYMESSAGESARRAY			INCV.INCENTIVE_MESSAGE_TAB
);


/*
DROP TYPE INCV.ACTIVITY_CONFIGURATION_TAB;
*/

CREATE OR REPLACE TYPE INCV.ACTIVITY_CONFIGURATION_TAB FORCE as table of INCV.ACTIVITY_CONFIGURATION_OBJ;


/*
DROP TYPE INCV.ACTIVITY_GRP_CONFIGURATION_OBJ;
*/

CREATE OR REPLACE TYPE INCV.ACTIVITY_GRP_CONFIGURATION_OBJ FORCE as object (
	ACTIVITYGROUPDESC               VARCHAR2(200),
	SORTORDERNO                     NUMBER,
	STARTDATE						DATE,
	ENDDATE							DATE,
	INCENTIVESVALUES                INCV.INCENTIVE_GOAL_TAB,
	ACTIVITYATTRIBUTEARRAY          INCV.ATTRIBUTE_CONFIGURATION_TAB,
	ACTIVITYARRAY              		INCV.ACTIVITY_CONFIGURATION_TAB
);


/*
DROP TYPE INCV.ACTIVITY_GRP_CONFIGURATION_TAB;
*/

CREATE OR REPLACE TYPE INCV.ACTIVITY_GRP_CONFIGURATION_TAB FORCE as table of INCV.ACTIVITY_GRP_CONFIGURATION_OBJ;


/*
DROP TYPE INCV.AHM_SUPPLIER_LIST_OBJ;
*/

CREATE OR REPLACE TYPE INCV.AHM_SUPPLIER_LIST_OBJ FORCE as object (
	AHMSUPPLIERID			NUMBER
);


/*
DROP TYPE INCV.AHM_SUPPLIER_LIST_TAB;
*/

CREATE OR REPLACE TYPE INCV.AHM_SUPPLIER_LIST_TAB FORCE as table of INCV.AHM_SUPPLIER_LIST_OBJ;


/*
DROP TYPE INCV.ATTRIBUTE_CONFIGURATION_OBJ;
*/

CREATE OR REPLACE TYPE INCV.ATTRIBUTE_CONFIGURATION_OBJ FORCE as object (
	ATTRIBUTENAME                   VARCHAR2(50),
	ATTRIBUTEVALUE                  VARCHAR2(4000),
	GENDER							VARCHAR2(1),
	MEMBERTYPE					    VARCHAR2(50),
	ATTRIBDATATYPEMNEMONIC          VARCHAR2(50),
	OVERRIDEVALUEARRAY	            INCV.INCENTIVE_OVERRIDE_VALUE_TAB
);


/*
DROP TYPE INCV.ATTRIBUTE_CONFIGURATION_TAB;
*/

CREATE OR REPLACE TYPE INCV.ATTRIBUTE_CONFIGURATION_TAB FORCE as table of INCV.ATTRIBUTE_CONFIGURATION_OBJ;


/*
DROP TYPE INCV.CHILD_ACTIVITY_CONFIG_OBJ;
*/

CREATE OR REPLACE TYPE INCV.CHILD_ACTIVITY_CONFIG_OBJ FORCE as object (
	ACTIVITYDESC					VARCHAR2(200),
	ACTIVITYTITLETXT				VARCHAR2(200),
	GENDER						    VARCHAR2(1),
	ACTIVITYTYPEMNEMONIC			VARCHAR2(50),
	STARTDATE						DATE,
	ENDDATE							DATE,
	NUMBEROFOCCURANCE				NUMBER,
	MINREQUIREDOCCURRENCE			NUMBER,
	SORTORDERNBR					NUMBER,
	REQUIREDYNIND                   VARCHAR2(1),
	ALTERNATIVE                     VARCHAR2(1),
	DISPLAYORDER                    NUMBER,
	ISREQUIREDFORGROUP              VARCHAR2(1),
	RELATIONTYPE                    VARCHAR2(20),
	INCENTIVESVALUES                INCV.INCENTIVE_GOAL_TAB,
	ACTIVITYATTRIBUTEARRAY          INCV.ATTRIBUTE_CONFIGURATION_TAB,
	ACTIVITYMESSAGESARRAY			INCV.INCENTIVE_MESSAGE_TAB
);


/*
DROP TYPE INCV.CHILD_ACTIVITY_CONFIG_TAB;
*/

CREATE OR REPLACE TYPE INCV.CHILD_ACTIVITY_CONFIG_TAB FORCE as table of INCV.CHILD_ACTIVITY_CONFIG_OBJ;


/*
DROP TYPE INCV.INCENTIVE_GOAL_OBJ;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_GOAL_OBJ FORCE as object (
	INCENTIVESTYPE						VARCHAR2(50),
	MINIMUMVALUE						NUMBER,
	MAXIMUMVALUE					    NUMBER,
	MEMBERTYPE					        VARCHAR2(50),
	OVERRIDEVALUEARRAY	                INCV.INCENTIVE_OVERRIDE_VALUE_TAB
);


/*
DROP TYPE INCV.INCENTIVE_GOAL_TAB;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_GOAL_TAB FORCE as table of INCV.INCENTIVE_GOAL_OBJ;


/*
DROP TYPE INCV.INCENTIVE_MESSAGEATTR_OBJ;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_MESSAGEATTR_OBJ FORCE as object (
	MESSAGEATTRIBUTENM                   VARCHAR2(50),
	MESSAGEATTRIBUTEVAL                  VARCHAR2(4000)
);


/*
DROP TYPE INCV.INCENTIVE_MESSAGEATTR_TAB;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_MESSAGEATTR_TAB FORCE as table of INCV.INCENTIVE_MESSAGEATTR_OBJ;


/*
DROP TYPE INCV.INCENTIVE_MESSAGE_OBJ;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_MESSAGE_OBJ FORCE as object (
	LANGUAGEMNEMONIC                  		VARCHAR2(50),
	LONGTITLETXT                 			VARCHAR2(4000),
	SHORTTITLETXT							VARCHAR2(255),
	ADDITIONALINFOTXT					    VARCHAR2(4000),
	INCENTIVEMESSAGEATTRARRAY        		INCV.INCENTIVE_MESSAGEATTR_TAB
);


/*
DROP TYPE INCV.INCENTIVE_MESSAGE_TAB;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_MESSAGE_TAB FORCE as table of INCV.INCENTIVE_MESSAGE_OBJ;


/*
DROP TYPE INCV.INCENTIVE_OVERRIDE_VALUE_OBJ;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_OVERRIDE_VALUE_OBJ FORCE as object (
	DIMENSIONTYPEMNEMONIC           VARCHAR2(50),
	DIMENSIONVAL					VARCHAR2(4000),
	OVERRIDEVAL					    VARCHAR2(4000)
);


/*
DROP TYPE INCV.INCENTIVE_OVERRIDE_VALUE_TAB;
*/

CREATE OR REPLACE TYPE INCV.INCENTIVE_OVERRIDE_VALUE_TAB FORCE as table of INCV.INCENTIVE_OVERRIDE_VALUE_OBJ;


/*
DROP TYPE INCV.MEMBERACTIVITYOCCURVAL_OBJ;
*/

CREATE OR REPLACE TYPE INCV.MEMBERACTIVITYOCCURVAL_OBJ
    FORCE
AS
   OBJECT (MemberTierMnemonic VARCHAR2 (50),
           GoalTypeMnemonic VARCHAR2 (50),
           EarnedRewardVal NUMBER (38),
           EARNEDOCCURRENCEVAL NUMBER (38),
           EARNEDACTIVITYVAL NUMBER (38),
           MAXREWARDVAL NUMBER (38),
           Redeemedrewardval NUMBER (38),
           Balancerewardval NUMBER (38),
           AccruedDate TIMESTAMP);;


/*
DROP TYPE INCV.MEMBERACTIVITYOCCURVAL_TAB;
*/

CREATE OR REPLACE TYPE INCV.MEMBERACTIVITYOCCURVAL_tab
    FORCE
IS
   TABLE OF MEMBERACTIVITYOCCURVAL_OBJ;


/*
DROP TYPE INCV.MEMBERELIGIBLEME_OBJ;
*/

CREATE OR REPLACE TYPE INCV.MEMBERELIGIBLEME_OBJ FORCE as object (
   MEMBERID                     NUMBER,
   AHMSUPPLIERID                NUMBER,
   PROGRAMSTARTDT       	      DATE,
   PROGRAMENDDT 		    	  DATE,
   MELIST              INCV.ME_OBJ_ARR
)
/


/*
DROP TYPE INCV.MEMBERELIGIBLEME_OBJ_ARR;
*/

CREATE OR REPLACE TYPE INCV.MEMBERELIGIBLEME_OBJ_ARR FORCE as table of INCV.MEMBERELIGIBLEME_OBJ;


/*
DROP TYPE INCV.MEMBERREDEMPTION_OBJ;
*/

CREATE OR REPLACE TYPE INCV."MEMBERREDEMPTION_OBJ"
    FORCE
IS
  OBJECT
  (
    Rewardid                NUMBER,
    RedemptionVal           NUMBER,
    RedemtionTypeMnemonic   VARCHAR2(40),
    RedemptionDt            TIMESTAMP(6),
    REDEMPTIONDESC          VARCHAR2(255),
    VOIDFLG                 VARCHAR2(2),
    RETURNCODE              NUMBER,
    RETURNMESSAGE           VARCHAR2(255),
    MemberRedemptionsKEY    NUMBER);


/*
DROP TYPE INCV.MEMBERREDEMPTION_TAB;
*/

CREATE OR REPLACE TYPE INCV."MEMBERREDEMPTION_TAB" FORCE IS TABLE OF MEMBERREDEMPTION_OBJ;


/*
DROP TYPE INCV.ME_OBJ;
*/

CREATE OR REPLACE TYPE INCV.ME_OBJ FORCE as object (
  MEID             NUMBER
);


/*
DROP TYPE INCV.ME_OBJ_ARR;
*/

CREATE OR REPLACE TYPE INCV.ME_OBJ_ARR FORCE as table of INCV.ME_OBJ;


/*
DROP TYPE INCV.NUMBERARRAY;
*/

CREATE OR REPLACE TYPE INCV.NUMBERARRAY FORCE IS TABLE OF NUMBER;;


/*
DROP TYPE INCV.PROGRAMINFO_OBJ;
*/

CREATE OR REPLACE TYPE INCV."PROGRAMINFO_OBJ" FORCE is object (ProgramId        Number,
                                                  MEMBERREDEMPTION MEMBERREDEMPTION_TAB);


/*
DROP TYPE INCV.PROGRAMINFO_TAB;
*/

CREATE OR REPLACE TYPE INCV."PROGRAMINFO_TAB" FORCE IS TABLE OF PROGRAMINFO_OBJ;


/*
DROP TYPE INCV.PROGRAMLIST_OBJ;
*/

CREATE OR REPLACE TYPE INCV.PROGRAMLIST_OBJ FORCE as object
(
	PROGRAMID NUMBER
);


/*
DROP TYPE INCV.PROGRAMLIST_TAB;
*/

CREATE OR REPLACE TYPE INCV.PROGRAMLIST_TAB FORCE as table of INCV.PROGRAMLIST_OBJ;


/*
DROP TYPE INCV.PROGRAM_CONFIGURATION_OBJ;
*/

CREATE OR REPLACE TYPE INCV.PROGRAM_CONFIGURATION_OBJ FORCE as object (
	STARTDATE						DATE,
	ENDDATE							DATE,
	DISPLAYNAME					    VARCHAR2(50),
	DISPLAYDATE						DATE,
	AHMSUPPLIERARRAY				INCV.AHM_SUPPLIER_LIST_TAB,
	PROGRAMATTRIBUTEARRAY           INCV.ATTRIBUTE_CONFIGURATION_TAB,
	REWARDARRAY                     INCV.REWARD_CONFIGURATION_TAB,
	INCENTIVEMESSAGESARRAY			INCV.INCENTIVE_MESSAGE_TAB
);


/*
DROP TYPE INCV.PROGRAM_CONFIGURATION_TAB;
*/

CREATE OR REPLACE TYPE INCV.PROGRAM_CONFIGURATION_TAB FORCE as table of INCV.PROGRAM_CONFIGURATION_OBJ;


/*
DROP TYPE INCV.REWARD_CONFIGURATION_OBJ;
*/

CREATE OR REPLACE TYPE INCV.REWARD_CONFIGURATION_OBJ FORCE as object (
	REWARDNAME					    VARCHAR2(200),
	STARTDATE						DATE,
	ENDDATE							DATE,
	NOOFACTIVITIESTOCOMPLETE   		NUMBER,
	REWARDTYPE                      VARCHAR2(50),
	SORTORDERNBR                    NUMBER,
	INCENTIVESVALUES				INCV.INCENTIVE_GOAL_TAB,
	REWARDATTRIBUTEARRAY			INCV.ATTRIBUTE_CONFIGURATION_TAB,
	ACTIVITYGROUPARRAY              INCV.ACTIVITY_GRP_CONFIGURATION_TAB,
	INCENTIVEMESSAGESARRAY			INCV.INCENTIVE_MESSAGE_TAB
);


/*
DROP TYPE INCV.REWARD_CONFIGURATION_TAB;
*/

CREATE OR REPLACE TYPE INCV.REWARD_CONFIGURATION_TAB FORCE as table of INCV.REWARD_CONFIGURATION_OBJ;


/*
DROP TYPE INCV.TIERPROGRESSION_OBJ;
*/

CREATE OR REPLACE TYPE INCV.TIERPROGRESSION_OBJ
    FORCE
AS
  OBJECT
  (
    RewardId               NUMBER,
	MemberTierMnemonic     VARCHAR2(50),
	GoalTypeMnemonic       VARCHAR2(50),
	EffStartDt             TIMESTAMP
  );


/*
DROP TYPE INCV.TIERPROGRESSION_TAB;
*/

CREATE OR REPLACE TYPE INCV.TIERPROGRESSION_TAB
    FORCE
IS
  TABLE OF TIERPROGRESSION_OBJ;


GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO ACTS_APPS;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO ACTS_APPS;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO ACTS_APPS;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO ACTS_APPS;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO ACTS_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO ACTS_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO ACTS_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO ACTS_USER;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_OBJ TO AETINCV_USER;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_TAB TO AETINCV_USER;

GRANT EXECUTE ON INCV.PROGRAMINFO_OBJ TO AETINCV_USER;

GRANT EXECUTE ON INCV.PROGRAMINFO_TAB TO AETINCV_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO CLMFIN;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO CLMFIN;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO CLMFIN;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO CLMFIN;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ TO CSID_DML;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ_ARR TO CSID_DML;

GRANT EXECUTE ON INCV.ME_OBJ TO CSID_DML;

GRANT EXECUTE ON INCV.ME_OBJ_ARR TO CSID_DML;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO CTLM_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO CTLM_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO CTLM_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO CTLM_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO ETLADMIN;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO ETLADMIN;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO ETLADMIN;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO ETLADMIN;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO FIXER WITH GRANT OPTION;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO FIXER WITH GRANT OPTION;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO FIXER WITH GRANT OPTION;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO FIXER WITH GRANT OPTION;

GRANT EXECUTE ON INCV.ACTIVITYCCCURENCELIST_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.ACTIVITYCCCURENCELIST_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.ACTIVITY_CONFIGURATION_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.ACTIVITY_CONFIGURATION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.ACTIVITY_GRP_CONFIGURATION_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.ACTIVITY_GRP_CONFIGURATION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.AHM_SUPPLIER_LIST_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.AHM_SUPPLIER_LIST_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.ATTRIBUTE_CONFIGURATION_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.ATTRIBUTE_CONFIGURATION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.CHILD_ACTIVITY_CONFIG_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.CHILD_ACTIVITY_CONFIG_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_GOAL_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_GOAL_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGEATTR_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGEATTR_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGE_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGE_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_OVERRIDE_VALUE_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.INCENTIVE_OVERRIDE_VALUE_TAB TO INCV_APP;

GRANT EXECUTE, DEBUG ON INCV.MEMBERACTIVITYOCCURVAL_OBJ TO INCV_APP;

GRANT EXECUTE, DEBUG ON INCV.MEMBERACTIVITYOCCURVAL_TAB TO INCV_APP;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO INCV_APP;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.ME_OBJ TO INCV_APP;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO INCV_APP;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.PROGRAMLIST_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.PROGRAMLIST_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.PROGRAM_CONFIGURATION_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.PROGRAM_CONFIGURATION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.REWARD_CONFIGURATION_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.REWARD_CONFIGURATION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.TIERPROGRESSION_OBJ TO INCV_APP;

GRANT EXECUTE ON INCV.TIERPROGRESSION_TAB TO INCV_APP;

GRANT EXECUTE ON INCV.ACTIVITYCCCURENCELIST_OBJ TO INCV_DEV;

GRANT EXECUTE ON INCV.ACTIVITYCCCURENCELIST_TAB TO INCV_DEV;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO INCV_DEV;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO INCV_DEV;

GRANT EXECUTE ON INCV.ME_OBJ TO INCV_DEV;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO INCV_DEV;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO INCV_DEV;

GRANT EXECUTE ON INCV.TIERPROGRESSION_OBJ TO INCV_DEV;

GRANT EXECUTE ON INCV.TIERPROGRESSION_TAB TO INCV_DEV;

GRANT EXECUTE ON INCV.ACTIVITYCCCURENCELIST_OBJ TO INCV_DML;

GRANT EXECUTE ON INCV.ACTIVITYCCCURENCELIST_TAB TO INCV_DML;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_OBJ TO INCV_DML;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_TAB TO INCV_DML;

GRANT EXECUTE ON INCV.ME_OBJ TO INCV_DML;

GRANT EXECUTE ON INCV.PROGRAMINFO_OBJ TO INCV_DML;

GRANT EXECUTE ON INCV.PROGRAMINFO_TAB TO INCV_DML;

GRANT EXECUTE ON INCV.TIERPROGRESSION_OBJ TO INCV_DML;

GRANT EXECUTE ON INCV.TIERPROGRESSION_TAB TO INCV_DML;

GRANT EXECUTE ON INCV.ME_OBJ TO INCV_READ;

GRANT EXECUTE, DEBUG ON INCV.NUMBERARRAY TO INCV_READ;

GRANT EXECUTE, DEBUG ON INCV.ACTIVITYCCCURENCELIST_OBJ TO INCV_USER;

GRANT EXECUTE, DEBUG ON INCV.ACTIVITYCCCURENCELIST_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.ACTIVITY_CONFIGURATION_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.ACTIVITY_CONFIGURATION_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.ACTIVITY_GRP_CONFIGURATION_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.ACTIVITY_GRP_CONFIGURATION_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.AHM_SUPPLIER_LIST_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.AHM_SUPPLIER_LIST_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.ATTRIBUTE_CONFIGURATION_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.ATTRIBUTE_CONFIGURATION_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.CHILD_ACTIVITY_CONFIG_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.CHILD_ACTIVITY_CONFIG_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_GOAL_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_GOAL_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGEATTR_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGEATTR_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGE_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGE_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_OVERRIDE_VALUE_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.INCENTIVE_OVERRIDE_VALUE_TAB TO INCV_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO INCV_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO INCV_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO INCV_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.PROGRAMLIST_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.PROGRAMLIST_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.PROGRAM_CONFIGURATION_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.PROGRAM_CONFIGURATION_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.REWARD_CONFIGURATION_OBJ TO INCV_USER;

GRANT EXECUTE ON INCV.REWARD_CONFIGURATION_TAB TO INCV_USER;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_OBJ TO ODS;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_TAB TO ODS;

GRANT EXECUTE ON INCV.PROGRAMINFO_OBJ TO ODS;

GRANT EXECUTE ON INCV.PROGRAMINFO_TAB TO ODS;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ TO ODS_DML;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ_ARR TO ODS_DML;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO ODS_DML;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO ODS_DML;

GRANT EXECUTE ON INCV.ME_OBJ TO ODS_DML;

GRANT EXECUTE ON INCV.ME_OBJ_ARR TO ODS_DML;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO ODS_DML;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO ODS_DML;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ TO ODS_READ;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ_ARR TO ODS_READ;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO ODS_READ;

GRANT EXECUTE ON INCV.MEMBERREDEMPTION_TAB TO ODS_READ;

GRANT EXECUTE ON INCV.ME_OBJ TO ODS_READ;

GRANT EXECUTE ON INCV.ME_OBJ_ARR TO ODS_READ;

GRANT EXECUTE, DEBUG ON INCV.NUMBERARRAY TO ODS_READ;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO ODS_READ;

GRANT EXECUTE ON INCV.PROGRAMINFO_TAB TO ODS_READ;

GRANT EXECUTE ON INCV.ACTIVITY_CONFIGURATION_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.ACTIVITY_CONFIGURATION_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.ACTIVITY_GRP_CONFIGURATION_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.ACTIVITY_GRP_CONFIGURATION_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.AHM_SUPPLIER_LIST_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.AHM_SUPPLIER_LIST_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.ATTRIBUTE_CONFIGURATION_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.ATTRIBUTE_CONFIGURATION_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.CHILD_ACTIVITY_CONFIG_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.CHILD_ACTIVITY_CONFIG_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_GOAL_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_GOAL_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGEATTR_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGEATTR_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGE_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_MESSAGE_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_OVERRIDE_VALUE_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.INCENTIVE_OVERRIDE_VALUE_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.MEMBERELIGIBLEME_OBJ_ARR TO ODS_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_OBJ TO ODS_USER;

GRANT EXECUTE, DEBUG ON INCV.MEMBERREDEMPTION_TAB TO ODS_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_OBJ TO ODS_USER;

GRANT EXECUTE, DEBUG ON INCV.PROGRAMINFO_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.PROGRAMLIST_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.PROGRAMLIST_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.PROGRAM_CONFIGURATION_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.PROGRAM_CONFIGURATION_TAB TO ODS_USER;

GRANT EXECUTE ON INCV.REWARD_CONFIGURATION_OBJ TO ODS_USER;

GRANT EXECUTE ON INCV.REWARD_CONFIGURATION_TAB TO ODS_USER;


-- EXIT;