-- SET ECHO ON

/*
ALTER TABLE INCV.ACTIVITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.ACTIVITY CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.ACTIVITY
(
  ACTIVITYID             NUMBER                 NOT NULL,
  ACTIVITYDESC           VARCHAR2(200 BYTE)     NOT NULL,
  ACTIVITYTITLETXT       VARCHAR2(200 BYTE)     NOT NULL,
  ACTIVITYTYPEMNEMONIC   VARCHAR2(50 BYTE)      NOT NULL,
  STARTDT                TIMESTAMP(6)           NOT NULL,
  ENDDT                  TIMESTAMP(6),
  NUMBEROFOCCURANCE      NUMBER                 NOT NULL,
  FREQUENCYMNEMONIC      VARCHAR2(20 BYTE),
  INSERTEDDT             TIMESTAMP(6)           NOT NULL,
  INSERTEDBY             VARCHAR2(30 BYTE)      NOT NULL,
  UPDATEDDT              TIMESTAMP(6),
  UPDATEDBY              VARCHAR2(30 BYTE),
  GENDER                 VARCHAR2(1 BYTE),
  MINREQUIREDOCCURRENCE  NUMBER                 DEFAULT 1                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEATTRIBUTE
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEATTRIBUTE CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEATTRIBUTE
(
  INCENTIVEGOALCATEGORYID         NUMBER        NOT NULL,
  INCENTIVEGOALCATEGORYMNEMONIC   VARCHAR2(20 BYTE) NOT NULL,
  INCENTIVEATTRIBUTENM            VARCHAR2(50 BYTE) NOT NULL,
  ACTIVITYATTRIBDATATYPEMNEMONIC  VARCHAR2(50 BYTE) NOT NULL,
  INCENTIVEATTRIBUTEVAL           VARCHAR2(4000 BYTE) NOT NULL,
  PARTICIPANTTYPEMNEMONIC         VARCHAR2(50 BYTE),
  INSERTEDDT                      TIMESTAMP(6)  NOT NULL,
  INSERTEDBY                      VARCHAR2(30 BYTE) NOT NULL,
  UPDATEDDT                       TIMESTAMP(6),
  UPDATEDBY                       VARCHAR2(30 BYTE),
  GENDER                          VARCHAR2(1 BYTE),
  INCENTIVEATTRIBUTESKEY          NUMBER,
  ATTRIBUTEVALJSONFLG             CHAR(1 BYTE)  DEFAULT 'N'                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

/*
ALTER TABLE INCV.MASTERMNEMONIC
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.MASTERMNEMONIC CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.MASTERMNEMONIC
(
  MASTERCODEMNEMONIC  VARCHAR2(50 BYTE)         NOT NULL,
  MASTERCODEDESC      VARCHAR2(200 BYTE)        NOT NULL,
  VOIDFLG             VARCHAR2(2 BYTE),
  INSERTEDDT          TIMESTAMP(6)              NOT NULL,
  INSERTEDBY          VARCHAR2(30 BYTE)         NOT NULL,
  UPDATEDDT           TIMESTAMP(6),
  UPDATEDBY           VARCHAR2(30 BYTE),
  MASTERGROUPCD       VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

/*
ALTER TABLE INCV.MASTERGROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.MASTERGROUP CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.MASTERGROUP
(
  MASTERGROUPCD    VARCHAR2(50 BYTE)            NOT NULL,
  MASTERGROUPDESC  VARCHAR2(200 BYTE)           NOT NULL,
  INSERTEDDT       TIMESTAMP(6)                 NOT NULL,
  INSERTEDBY       VARCHAR2(30 BYTE)            NOT NULL,
  UPDATEDDT        TIMESTAMP(6),
  UPDATEDBY        VARCHAR2(30 BYTE),
  VOIDFLG          VARCHAR2(2 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCVSQLSTATEMENT_TMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCVSQLSTATEMENT_TMP CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCVSQLSTATEMENT_TMP
(
  SEQUENCENO       NUMBER,
  STATEMENTTYPECD  VARCHAR2(10 BYTE),
  TABLENAME        VARCHAR2(30 BYTE),
  SQLTXT           VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVERUNDETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVERUNDETAIL CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVERUNDETAIL
(
  INCENTIVERUNID     NUMBER                     NOT NULL,
  AHMSUPPLIERID      NUMBER                     NOT NULL,
  RUNTYPEMNEMONIC    VARCHAR2(50 BYTE)          NOT NULL,
  RUNSTARTDT         TIMESTAMP(6)               NOT NULL,
  RUNENDDT           TIMESTAMP(6),
  TOTALBATCHCNT      NUMBER                     NOT NULL,
  PROCESSEDBATCHCNT  NUMBER,
  RUNSTATUSMNEMONIC  VARCHAR2(50 BYTE),
  VOIDFLG            VARCHAR2(2 BYTE),
  INSERTEDDT         TIMESTAMP(6)               NOT NULL,
  INSERTEDBY         VARCHAR2(30 BYTE)          NOT NULL,
  UPDATEDDT          TIMESTAMP(6),
  UPDATEDBY          VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.ACTIVITYGROUPACTIVITYXREF
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.ACTIVITYGROUPACTIVITYXREF CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.ACTIVITYGROUPACTIVITYXREF
(
  ACTIVITYGROUPID  NUMBER                       NOT NULL,
  ACTIVITYID       NUMBER                       NOT NULL,
  REQUIREDYNIND    VARCHAR2(1 BYTE),
  SORTORDERNBR     NUMBER,
  INSERTEDDT       TIMESTAMP(6)                 NOT NULL,
  INSERTEDBY       VARCHAR2(30 BYTE)            NOT NULL,
  UPDATEDDT        TIMESTAMP(6),
  UPDATEDBY        VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.ACTIVITYGROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.ACTIVITYGROUP CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.ACTIVITYGROUP
(
  ACTIVITYGROUPID    NUMBER                     NOT NULL,
  ACTIVITYGROUPDESC  VARCHAR2(200 BYTE)         NOT NULL,
  STARTDT            TIMESTAMP(6)               NOT NULL,
  ENDDT              TIMESTAMP(6),
  INSERTEDDT         TIMESTAMP(6)               NOT NULL,
  INSERTEDBY         VARCHAR2(30 BYTE)          NOT NULL,
  UPDATEDDT          TIMESTAMP(6),
  UPDATEDBY          VARCHAR2(30 BYTE),
  NOTREQUIREDCOUNT   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.ACTIVITYDETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.ACTIVITYDETAIL CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.ACTIVITYDETAIL
(
  ACTIVITYID              NUMBER                NOT NULL,
  DEPENDENTACTIVITYCOUNT  NUMBER                NOT NULL,
  INSERTEDDT              TIMESTAMP(6)          NOT NULL,
  INSERTEDBY              VARCHAR2(30 BYTE)     NOT NULL,
  UPDATEDDT               TIMESTAMP(6),
  UPDATEDBY               VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEOVERRIDE
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEOVERRIDE CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEOVERRIDE
(
  INCENTIVEOVERRIDESKEY     NUMBER              NOT NULL,
  OVERRIDECATEGORYID        NUMBER              NOT NULL,
  OVERRIDECATEGORYMNEMONIC  VARCHAR2(50 BYTE)   NOT NULL,
  DIMENSIONTYPEMNEMONIC     VARCHAR2(50 BYTE)   NOT NULL,
  DIMENSIONVAL              VARCHAR2(4000 BYTE) NOT NULL,
  OVERRIDEVAL               VARCHAR2(4000 BYTE),
  PRIORITYNBR               NUMBER,
  VOIDFLG                   VARCHAR2(2 BYTE),
  INSERTEDDT                TIMESTAMP(6)        DEFAULT systimestamp          NOT NULL,
  INSERTEDBY                VARCHAR2(30 BYTE)   DEFAULT USER                  NOT NULL,
  UPDATEDDT                 TIMESTAMP(6)        DEFAULT systimestamp,
  UPDATEDBY                 VARCHAR2(30 BYTE)   DEFAULT USER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEMESSAGEDEFAULTATTR
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEMESSAGEDEFAULTATTR CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEMESSAGEDEFAULTATTR
(
  INCENTIVEMSGDEFAULTATTRID  NUMBER,
  ATTRIBUTECATGEORY          VARCHAR2(50 BYTE)  NOT NULL,
  ATTRIBUTENM                VARCHAR2(50 BYTE)  NOT NULL,
  ATTRIBUTETXT               VARCHAR2(4000 BYTE) NOT NULL,
  LANGUAGEMNEMONIC           VARCHAR2(50 BYTE)  NOT NULL,
  VOIDFLG                    VARCHAR2(2 BYTE)   NOT NULL,
  INSERTEDDT                 TIMESTAMP(6)       NOT NULL,
  INSERTEDBY                 VARCHAR2(30 BYTE)  NOT NULL,
  UPDATEDDT                  TIMESTAMP(6)       NOT NULL,
  UPDATEDBY                  VARCHAR2(30 BYTE)  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEMESSAGEATTR
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEMESSAGEATTR CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEMESSAGEATTR
(
  INCENTIVEMESSAGEID   NUMBER                   NOT NULL,
  MESSAGEATTRIBUTENM   VARCHAR2(50 BYTE)        NOT NULL,
  MESSAGEATTRIBUTEVAL  VARCHAR2(4000 BYTE),
  VOIDFLG              VARCHAR2(2 BYTE),
  INSERTEDDT           TIMESTAMP(6)             NOT NULL,
  INSERTEDBY           VARCHAR2(30 BYTE)        NOT NULL,
  UPDATEDDT            TIMESTAMP(6),
  UPDATEDBY            VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEMESSAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEMESSAGE CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEMESSAGE
(
  INCENTIVEMESSAGEID             NUMBER         NOT NULL,
  AHMSUPPLIERID                  NUMBER,
  INCENTIVEGOALCATEGORYID        NUMBER,
  INCENTIVEGOALCATEGORYMNEMONIC  VARCHAR2(20 BYTE),
  LANGUAGEMNEMONIC               VARCHAR2(50 BYTE) NOT NULL,
  LONGTITLETXT                   VARCHAR2(4000 BYTE),
  SHORTTITLETXT                  VARCHAR2(255 BYTE),
  ADDITIONALINFOTXT              VARCHAR2(4000 BYTE),
  VOIDFLG                        VARCHAR2(2 BYTE),
  INSERTEDDT                     TIMESTAMP(6)   NOT NULL,
  INSERTEDBY                     VARCHAR2(30 BYTE) NOT NULL,
  UPDATEDDT                      TIMESTAMP(6),
  UPDATEDBY                      VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEGOALVALUE
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEGOALVALUE CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEGOALVALUE
(
  INCENTIVEGOALCATEGORYID        NUMBER         NOT NULL,
  INCENTIVEGOALCATEGORYMNEMONIC  VARCHAR2(20 BYTE) NOT NULL,
  PARTICIPANTTYPEMNEMONIC        VARCHAR2(50 BYTE) NOT NULL,
  INCENTIVEGOALMINVAL            NUMBER         NOT NULL,
  INCENTIVEGOALMAXVAL            NUMBER,
  INSERTEDDT                     TIMESTAMP(6)   NOT NULL,
  INSERTEDBY                     VARCHAR2(30 BYTE) NOT NULL,
  UPDATEDDT                      TIMESTAMP(6),
  UPDATEDBY                      VARCHAR2(30 BYTE),
  INCENTIVEGOALVALUESKEY         NUMBER,
  GOALTYPEMNEMONIC               VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEGOALTYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEGOALTYPE CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEGOALTYPE
(
  INCENTIVEGOALTYPESKEY   NUMBER                NOT NULL,
  GOALCATEGORYIDENTIFIER  NUMBER,
  GOALCATEGORYMNEMONIC    VARCHAR2(50 BYTE)     NOT NULL,
  GOALTYPEMNEMONIC        VARCHAR2(50 BYTE),
  VOIDFLG                 CHAR(2 BYTE)          NOT NULL,
  INSERTEDDT              TIMESTAMP(6)          DEFAULT systimestamp          NOT NULL,
  INSERTEDBY              VARCHAR2(30 BYTE)     DEFAULT USER                  NOT NULL,
  UPDATEDDT               TIMESTAMP(6)          DEFAULT systimestamp,
  UPDATEDBY               VARCHAR2(30 BYTE)     DEFAULT USER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEELIGIBILITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEELIGIBILITY CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEELIGIBILITY
(
  INCVELIGIBILITYSKEY           NUMBER          NOT NULL,
  ELIGIBILITYEXPRMNEMONIC       VARCHAR2(500 BYTE) DEFAULT NULL,
  AHMSUPPLIERID                 NUMBER,
  INCVELIGIBLECATEGORYID        NUMBER          NOT NULL,
  SUPPRESSIONIND                CHAR(1 BYTE)    NOT NULL,
  STARTDT                       TIMESTAMP(6)    NOT NULL,
  ENDDT                         TIMESTAMP(6),
  INSERTEDDT                    TIMESTAMP(6)    NOT NULL,
  INSERTEDBY                    VARCHAR2(30 BYTE) NOT NULL,
  UPDATEDDT                     TIMESTAMP(6),
  UPDATEDBY                     VARCHAR2(30 BYTE),
  VOIDFLG                       VARCHAR2(2 BYTE) NOT NULL,
  INCVELIGIBLECATEGORYMNEMONIC  VARCHAR2(25 BYTE) NOT NULL,
  PRIORITY                      NUMBER          DEFAULT 1
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.INCENTIVEATTRIBUTEVAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.INCENTIVEATTRIBUTEVAL CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.INCENTIVEATTRIBUTEVAL
(
  INCENTIVEATTRIBUTEVALSKEY  NUMBER,
  INCENTIVEATTRIBUTESKEY     NUMBER,
  INCENTIVEATTRIBUTEVALJSON  CLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.PROGRAM
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.PROGRAM CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.PROGRAM
(
  PROGRAMID           NUMBER                    NOT NULL,
  PROGRAMNM           VARCHAR2(50 BYTE)         NOT NULL,
  PROGRAMEFFECTIVEDT  TIMESTAMP(6)              NOT NULL,
  PROGRAMENDDT        TIMESTAMP(6)              NOT NULL,
  INSERTEDDT          TIMESTAMP(6)              NOT NULL,
  INSERTEDBY          VARCHAR2(30 BYTE)         NOT NULL,
  UPDATEDDT           TIMESTAMP(6),
  UPDATEDBY           VARCHAR2(30 BYTE),
  DISPLAYDT           TIMESTAMP(6)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.SUPPLIERPROGRAMASSOC
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.SUPPLIERPROGRAMASSOC CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.SUPPLIERPROGRAMASSOC
(
  AHMSUPPLIERID              NUMBER             NOT NULL,
  PROGRAMID                  NUMBER             NOT NULL,
  EFFECTIVEDT                TIMESTAMP(6)       NOT NULL,
  ENDDT                      TIMESTAMP(6),
  INSERTEDDT                 TIMESTAMP(6)       NOT NULL,
  INSERTEDBY                 VARCHAR2(30 BYTE)  NOT NULL,
  UPDATEDDT                  TIMESTAMP(6),
  UPDATEDBY                  VARCHAR2(30 BYTE),
  SPOUSETREATEDASEMPIND      CHAR(1 BYTE),
  ISSPOUSEPARTNERAPPLICABLE  VARCHAR2(1 BYTE)   DEFAULT 'N'                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.REWARDACTIVITYXREF
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.REWARDACTIVITYXREF CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.REWARDACTIVITYXREF
(
  REWARDID                NUMBER                NOT NULL,
  ACTIVITYID              NUMBER                NOT NULL,
  ASSOCIATIONEFFECTIVEDT  TIMESTAMP(6)          NOT NULL,
  ASSOCIATIONENDDT        TIMESTAMP(6),
  SORTORDERNBR            NUMBER,
  REQUIREDYNIND           VARCHAR2(1 BYTE)      NOT NULL,
  INSERTEDDT              TIMESTAMP(6)          NOT NULL,
  INSERTEDBY              VARCHAR2(30 BYTE)     NOT NULL,
  UPDATEDDT               TIMESTAMP(6),
  UPDATEDBY               VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.REWARDACTIVITYGROUPXREF
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.REWARDACTIVITYGROUPXREF CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.REWARDACTIVITYGROUPXREF
(
  REWARDID                NUMBER                NOT NULL,
  ACTIVITYGROUPID         NUMBER                NOT NULL,
  ASSOCIATIONEFFECTIVEDT  TIMESTAMP(6)          NOT NULL,
  ASSOCIATIONENDDT        TIMESTAMP(6),
  SORTORDERNBR            NUMBER,
  INSERTEDDT              TIMESTAMP(6)          NOT NULL,
  INSERTEDBY              VARCHAR2(30 BYTE)     NOT NULL,
  UPDATEDDT               TIMESTAMP(6),
  UPDATEDBY               VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.REWARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.REWARD CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.REWARD
(
  REWARDID                  NUMBER              NOT NULL,
  REWARDNM                  VARCHAR2(200 BYTE)  NOT NULL,
  PROGRAMID                 NUMBER              NOT NULL,
  SORTORDERNBR              NUMBER              NOT NULL,
  NOOFACTIVITIESTOCOMPLETE  NUMBER,
  REWARDEFFECTIVEDT         TIMESTAMP(6)        NOT NULL,
  REWARDENDDT               TIMESTAMP(6),
  INSERTEDDT                TIMESTAMP(6)        NOT NULL,
  INSERTEDBY                VARCHAR2(30 BYTE)   NOT NULL,
  UPDATEDDT                 TIMESTAMP(6),
  UPDATEDBY                 VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


/*
ALTER TABLE INCV.RELATEDACTIVITYXREF
 DROP PRIMARY KEY CASCADE;

DROP TABLE INCV.RELATEDACTIVITYXREF CASCADE CONSTRAINTS;
*/

CREATE TABLE INCV.RELATEDACTIVITYXREF
(
  ACTIVITYID            NUMBER                  NOT NULL,
  RELATEDACTIVITYID     NUMBER                  NOT NULL,
  REQUIREDYNIND         VARCHAR2(1 BYTE)        NOT NULL,
  RELATIONTYPEMNEMONIC  VARCHAR2(50 BYTE)       NOT NULL,
  INSERTEDDT            TIMESTAMP(6)            NOT NULL,
  INSERTEDBY            VARCHAR2(30 BYTE)       NOT NULL,
  UPDATEDDT             TIMESTAMP(6),
  UPDATEDBY             VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX INCV.INCVSQLSTATEMENT_TMP_IDX01 ON INCV.INCVSQLSTATEMENT_TMP
(STATEMENTTYPECD, TABLENAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.INCVSQLSTATEMENT_TMP_PK ON INCV.INCVSQLSTATEMENT_TMP
(SEQUENCENO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XAK01INCENTIVEMSGDEFAULTATTR ON INCV.INCENTIVEMESSAGEDEFAULTATTR
(ATTRIBUTECATGEORY, ATTRIBUTENM, LANGUAGEMNEMONIC)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XAK01XPKINCENTIVEMESSAGE ON INCV.INCENTIVEMESSAGE
(AHMSUPPLIERID, INCENTIVEGOALCATEGORYID, INCENTIVEGOALCATEGORYMNEMONIC, LANGUAGEMNEMONIC)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XAK1ELIGIBLEACTIVITY ON INCV.INCENTIVEELIGIBILITY
(AHMSUPPLIERID, INCVELIGIBLECATEGORYMNEMONIC, INCVELIGIBLECATEGORYID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XAK1INCENTIVEGOALTYPE ON INCV.INCENTIVEGOALTYPE
(GOALCATEGORYMNEMONIC, GOALTYPEMNEMONIC, GOALCATEGORYIDENTIFIER)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XAK1INCENTIVEOVERRIDE ON INCV.INCENTIVEOVERRIDE
(OVERRIDECATEGORYID, OVERRIDECATEGORYMNEMONIC, DIMENSIONTYPEMNEMONIC, DIMENSIONVAL)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIE1ACTIVITYGROUPACTIVITYXREF ON INCV.ACTIVITYGROUPACTIVITYXREF
(ACTIVITYGROUPID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIE1ELIGIBLEACTIVITY ON INCV.INCENTIVEELIGIBILITY
(INCVELIGIBLECATEGORYMNEMONIC, INCVELIGIBLECATEGORYID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XIE1INCENTIVEATTRIBUTE ON INCV.INCENTIVEATTRIBUTE
(INCENTIVEGOALCATEGORYID, INCENTIVEGOALCATEGORYMNEMONIC, INCENTIVEATTRIBUTENM, PARTICIPANTTYPEMNEMONIC, GENDER)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XIE1INCENTIVEGOALVALUE ON INCV.INCENTIVEGOALVALUE
(INCENTIVEGOALCATEGORYID, INCENTIVEGOALCATEGORYMNEMONIC, PARTICIPANTTYPEMNEMONIC, GOALTYPEMNEMONIC)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIE1RELATEDACTIVITYXREF ON INCV.RELATEDACTIVITYXREF
(ACTIVITYID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIE2ACTIVITYGROUPACTIVITYXREF ON INCV.ACTIVITYGROUPACTIVITYXREF
(ACTIVITYID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIE2RELATEDACTIVITYXREF ON INCV.RELATEDACTIVITYXREF
(RELATEDACTIVITYID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIEINCENTIVERUNDETAIL ON INCV.INCENTIVERUNDETAIL
(AHMSUPPLIERID, RUNTYPEMNEMONIC)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1INCENTIVEATTRIBUTE ON INCV.INCENTIVEATTRIBUTE
(INCENTIVEGOALCATEGORYID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1INCENTIVEGOALVALUE ON INCV.INCENTIVEGOALVALUE
(INCENTIVEGOALCATEGORYID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1INCENTIVEMESSAGEATTR ON INCV.INCENTIVEMESSAGEATTR
(INCENTIVEMESSAGEID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1MASTERMNEMONIC ON INCV.MASTERMNEMONIC
(MASTERGROUPCD)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1REWARD ON INCV.REWARD
(PROGRAMID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1REWARDACTIVITYGROUPXREF ON INCV.REWARDACTIVITYGROUPXREF
(REWARDID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF1REWARDACTIVITYXREF ON INCV.REWARDACTIVITYXREF
(REWARDID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF2REWARDACTIVITYGROUPXREF ON INCV.REWARDACTIVITYGROUPXREF
(ACTIVITYGROUPID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF2REWARDACTIVITYXREF ON INCV.REWARDACTIVITYXREF
(ACTIVITYID)
LOGGING
NOPARALLEL;


CREATE INDEX INCV.XIF2SUPPLIERPROGRAMASSOC ON INCV.SUPPLIERPROGRAMASSOC
(PROGRAMID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKACTIVITY ON INCV.ACTIVITY
(ACTIVITYID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKACTIVITYDETAIL ON INCV.ACTIVITYDETAIL
(ACTIVITYID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKACTIVITYGROUP ON INCV.ACTIVITYGROUP
(ACTIVITYGROUPID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKACTIVITYGROUPACTIVITYXREF ON INCV.ACTIVITYGROUPACTIVITYXREF
(ACTIVITYGROUPID, ACTIVITYID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKELIGIBLEACTIVITY ON INCV.INCENTIVEELIGIBILITY
(INCVELIGIBILITYSKEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEATTRIBUTE ON INCV.INCENTIVEATTRIBUTE
(INCENTIVEATTRIBUTESKEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEATTRIBUTEVAL ON INCV.INCENTIVEATTRIBUTEVAL
(INCENTIVEATTRIBUTEVALSKEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEGOALTYPE ON INCV.INCENTIVEGOALTYPE
(INCENTIVEGOALTYPESKEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEGOALVALUE ON INCV.INCENTIVEGOALVALUE
(INCENTIVEGOALVALUESKEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEMESSAGE ON INCV.INCENTIVEMESSAGE
(INCENTIVEMESSAGEID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEMESSAGEATTR ON INCV.INCENTIVEMESSAGEATTR
(INCENTIVEMESSAGEID, MESSAGEATTRIBUTENM)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEMSGDEFAULTATTR ON INCV.INCENTIVEMESSAGEDEFAULTATTR
(INCENTIVEMSGDEFAULTATTRID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVEOVERRIDE ON INCV.INCENTIVEOVERRIDE
(INCENTIVEOVERRIDESKEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKINCENTIVERUNDETAIL ON INCV.INCENTIVERUNDETAIL
(INCENTIVERUNID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKMASTERGROUP ON INCV.MASTERGROUP
(MASTERGROUPCD)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKMASTERMNEMONIC ON INCV.MASTERMNEMONIC
(MASTERCODEMNEMONIC)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKPROGRAM ON INCV.PROGRAM
(PROGRAMID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKRELATEDACTIVITYXREF ON INCV.RELATEDACTIVITYXREF
(ACTIVITYID, RELATEDACTIVITYID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKREWARD ON INCV.REWARD
(REWARDID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKREWARDACTIVITYGROUPXREF ON INCV.REWARDACTIVITYGROUPXREF
(REWARDID, ACTIVITYGROUPID, ASSOCIATIONEFFECTIVEDT)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKREWARDACTIVITYXREF ON INCV.REWARDACTIVITYXREF
(REWARDID, ACTIVITYID, ASSOCIATIONEFFECTIVEDT)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INCV.XPKSUPPLIERPROGRAMASSOC ON INCV.SUPPLIERPROGRAMASSOC
(AHMSUPPLIERID, PROGRAMID, EFFECTIVEDT)
LOGGING
NOPARALLEL;


ALTER TABLE INCV.ACTIVITY ADD (
  CONSTRAINT XPKACTIVITY
 PRIMARY KEY
 (ACTIVITYID));

ALTER TABLE INCV.INCENTIVEATTRIBUTE ADD (
  CONSTRAINT XPKINCENTIVEATTRIBUTE
 PRIMARY KEY
 (INCENTIVEATTRIBUTESKEY));

ALTER TABLE INCV.MASTERMNEMONIC ADD (
  CONSTRAINT MASTERMNEMONIC_CHK01
 CHECK (VOIDFLG IN ('IN', 'EX')),
  CONSTRAINT XPKMASTERMNEMONIC
 PRIMARY KEY
 (MASTERCODEMNEMONIC));

ALTER TABLE INCV.MASTERGROUP ADD (
  CONSTRAINT MASTERGROUP_CHK01
 CHECK (VOIDFLG IN ('IN', 'EX')),
  CONSTRAINT XPKMASTERGROUP
 PRIMARY KEY
 (MASTERGROUPCD));

ALTER TABLE INCV.INCVSQLSTATEMENT_TMP ADD (
  CONSTRAINT INCVSQLSTATEMENT_TMP_PK
 PRIMARY KEY
 (SEQUENCENO));

ALTER TABLE INCV.INCENTIVERUNDETAIL ADD (
  CONSTRAINT INCENTIVERUNDETAIL_CHK01
 CHECK (VOIDFLG IN ('IN', 'EX')),
  CONSTRAINT XPKINCENTIVERUNDETAIL
 PRIMARY KEY
 (INCENTIVERUNID));

ALTER TABLE INCV.ACTIVITYGROUPACTIVITYXREF ADD (
  CONSTRAINT XPKACTIVITYGROUPACTIVITYXREF
 PRIMARY KEY
 (ACTIVITYGROUPID, ACTIVITYID));

ALTER TABLE INCV.ACTIVITYGROUP ADD (
  CONSTRAINT XPKACTIVITYGROUP
 PRIMARY KEY
 (ACTIVITYGROUPID));

ALTER TABLE INCV.ACTIVITYDETAIL ADD (
  CONSTRAINT XPKACTIVITYDETAIL
 PRIMARY KEY
 (ACTIVITYID));

ALTER TABLE INCV.INCENTIVEOVERRIDE ADD (
  CONSTRAINT XPKINCENTIVEOVERRIDE
 PRIMARY KEY
 (INCENTIVEOVERRIDESKEY),
  CONSTRAINT XAK1INCENTIVEOVERRIDE
 UNIQUE (OVERRIDECATEGORYID, OVERRIDECATEGORYMNEMONIC, DIMENSIONTYPEMNEMONIC, DIMENSIONVAL));

ALTER TABLE INCV.INCENTIVEMESSAGEDEFAULTATTR ADD (
  CONSTRAINT XPKINCENTIVEMSGDEFAULTATTR
 PRIMARY KEY
 (INCENTIVEMSGDEFAULTATTRID));

ALTER TABLE INCV.INCENTIVEMESSAGEATTR ADD (
  CONSTRAINT INCENTIVEMESSAGEATTR_CHK01
 CHECK (VOIDFLG IN ('IN', 'EX')),
  CONSTRAINT XPKINCENTIVEMESSAGEATTR
 PRIMARY KEY
 (INCENTIVEMESSAGEID, MESSAGEATTRIBUTENM));

ALTER TABLE INCV.INCENTIVEMESSAGE ADD (
  CONSTRAINT INCENTIVEMESSAGE_CHK01
 CHECK (VOIDFLG IN ('IN', 'EX')),
  CONSTRAINT XPKINCENTIVEMESSAGE
 PRIMARY KEY
 (INCENTIVEMESSAGEID));

ALTER TABLE INCV.INCENTIVEGOALVALUE ADD (
  CONSTRAINT XPKINCENTIVEGOALVALUE
 PRIMARY KEY
 (INCENTIVEGOALVALUESKEY),
  CONSTRAINT XIE1INCENTIVEGOALVALUE
 UNIQUE (INCENTIVEGOALCATEGORYID, INCENTIVEGOALCATEGORYMNEMONIC, PARTICIPANTTYPEMNEMONIC, GOALTYPEMNEMONIC));

ALTER TABLE INCV.INCENTIVEGOALTYPE ADD (
  CONSTRAINT XPKINCENTIVEGOALTYPE
 PRIMARY KEY
 (INCENTIVEGOALTYPESKEY),
  CONSTRAINT XAK1INCENTIVEGOALTYPE
 UNIQUE (GOALCATEGORYIDENTIFIER, GOALCATEGORYMNEMONIC, GOALTYPEMNEMONIC));

ALTER TABLE INCV.INCENTIVEELIGIBILITY ADD (
  CONSTRAINT ELIGIBLEACTIVITY_CHK01
 CHECK (VOIDFLG IN ('IN', 'EX')),
  CONSTRAINT XPKELIGIBLEACTIVITY
 PRIMARY KEY
 (INCVELIGIBILITYSKEY),
  CONSTRAINT XAK1ELIGIBLEACTIVITY
 UNIQUE (AHMSUPPLIERID, INCVELIGIBLECATEGORYMNEMONIC, INCVELIGIBLECATEGORYID));

ALTER TABLE INCV.INCENTIVEATTRIBUTEVAL ADD (
  CONSTRAINT XPKINCENTIVEATTRIBUTEVAL
 PRIMARY KEY
 (INCENTIVEATTRIBUTEVALSKEY));

ALTER TABLE INCV.PROGRAM ADD (
  CONSTRAINT XPKPROGRAM
 PRIMARY KEY
 (PROGRAMID));

ALTER TABLE INCV.SUPPLIERPROGRAMASSOC ADD (
  CONSTRAINT XPKSUPPLIERPROGRAMASSOC
 PRIMARY KEY
 (AHMSUPPLIERID, PROGRAMID, EFFECTIVEDT));

ALTER TABLE INCV.REWARDACTIVITYXREF ADD (
  CONSTRAINT XPKREWARDACTIVITYXREF
 PRIMARY KEY
 (REWARDID, ACTIVITYID, ASSOCIATIONEFFECTIVEDT));

ALTER TABLE INCV.REWARDACTIVITYGROUPXREF ADD (
  CONSTRAINT XPKREWARDACTIVITYGROUPXREF
 PRIMARY KEY
 (REWARDID, ACTIVITYGROUPID, ASSOCIATIONEFFECTIVEDT));

ALTER TABLE INCV.REWARD ADD (
  CONSTRAINT XPKREWARD
 PRIMARY KEY
 (REWARDID));

ALTER TABLE INCV.RELATEDACTIVITYXREF ADD (
  CONSTRAINT XPKRELATEDACTIVITYXREF
 PRIMARY KEY
 (ACTIVITYID, RELATEDACTIVITYID));

ALTER TABLE INCV.ACTIVITY ADD (
  CONSTRAINT ACTVYACTVTYP_FK_MASTERMNEMONIC 
 FOREIGN KEY (ACTIVITYTYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC),
  CONSTRAINT ACTVYFREQ_FK_MASTERMNEMONIC 
 FOREIGN KEY (FREQUENCYMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

ALTER TABLE INCV.INCENTIVEATTRIBUTE ADD (
  CONSTRAINT INCENGOALATR_FK_MASTERMNEMONIC 
 FOREIGN KEY (INCENTIVEGOALCATEGORYMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC),
  CONSTRAINT PARTTYPCD_FK_MASTERMNEMONIC 
 FOREIGN KEY (PARTICIPANTTYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC),
  CONSTRAINT INCENGOALATRDAT_FK_MASTERMNEMO 
 FOREIGN KEY (ACTIVITYATTRIBDATATYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

ALTER TABLE INCV.MASTERMNEMONIC ADD (
  CONSTRAINT MASTERMNEMONIC_FK_MASTERGROUP 
 FOREIGN KEY (MASTERGROUPCD) 
 REFERENCES INCV.MASTERGROUP (MASTERGROUPCD));

ALTER TABLE INCV.INCENTIVERUNDETAIL ADD (
  CONSTRAINT XIF1INCENTIVERUNDETAIL 
 FOREIGN KEY (RUNTYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC),
  CONSTRAINT XIF2INCENTIVERUNDETAIL 
 FOREIGN KEY (RUNSTATUSMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

ALTER TABLE INCV.ACTIVITYGROUPACTIVITYXREF ADD (
  CONSTRAINT XFKACTIVITYGROUPID 
 FOREIGN KEY (ACTIVITYGROUPID) 
 REFERENCES INCV.ACTIVITYGROUP (ACTIVITYGROUPID),
  CONSTRAINT XFKACTIVITYID 
 FOREIGN KEY (ACTIVITYID) 
 REFERENCES INCV.ACTIVITY (ACTIVITYID));

ALTER TABLE INCV.ACTIVITYDETAIL ADD (
  CONSTRAINT ACTVTYDTL_FK_ACTVTY 
 FOREIGN KEY (ACTIVITYID) 
 REFERENCES INCV.ACTIVITY (ACTIVITYID));

ALTER TABLE INCV.INCENTIVEOVERRIDE ADD (
  CONSTRAINT XFK3INCENTIVEOVERRIDE 
 FOREIGN KEY (OVERRIDECATEGORYMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

ALTER TABLE INCV.INCENTIVEMESSAGEATTR ADD (
  CONSTRAINT INCVMSGATTR_FK_INCVMSG 
 FOREIGN KEY (INCENTIVEMESSAGEID) 
 REFERENCES INCV.INCENTIVEMESSAGE (INCENTIVEMESSAGEID));

ALTER TABLE INCV.INCENTIVEGOALVALUE ADD (
  CONSTRAINT INCENVALPART_FK_MASTERMNEMONIC 
 FOREIGN KEY (PARTICIPANTTYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC),
  CONSTRAINT INCENGOALCAT_FK_MASTERMNEMONIC 
 FOREIGN KEY (INCENTIVEGOALCATEGORYMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

ALTER TABLE INCV.INCENTIVEGOALTYPE ADD (
  CONSTRAINT XFKINCENTIVEGOALTYPE 
 FOREIGN KEY (GOALCATEGORYMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC),
  CONSTRAINT XFK1INCENTIVEGOALTYPE 
 FOREIGN KEY (GOALCATEGORYIDENTIFIER) 
 REFERENCES INCV.REWARD (REWARDID),
  CONSTRAINT XFK2INCENTIVEGOALTYPE 
 FOREIGN KEY (GOALTYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

ALTER TABLE INCV.INCENTIVEATTRIBUTEVAL ADD (
  CONSTRAINT XFKINCENTIVEATTRIBUTEVAL 
 FOREIGN KEY (INCENTIVEATTRIBUTESKEY) 
 REFERENCES INCV.INCENTIVEATTRIBUTE (INCENTIVEATTRIBUTESKEY));

ALTER TABLE INCV.SUPPLIERPROGRAMASSOC ADD (
  CONSTRAINT SUPPLIERGRPPGMASSOC_FK_PROGRAM 
 FOREIGN KEY (PROGRAMID) 
 REFERENCES INCV.PROGRAM (PROGRAMID));

ALTER TABLE INCV.REWARDACTIVITYXREF ADD (
  CONSTRAINT REWARDACTIVITYXREF_FK_REWARD 
 FOREIGN KEY (REWARDID) 
 REFERENCES INCV.REWARD (REWARDID),
  CONSTRAINT REWARDACTIVITYXREF_FK_ACTIVITY 
 FOREIGN KEY (ACTIVITYID) 
 REFERENCES INCV.ACTIVITY (ACTIVITYID));

ALTER TABLE INCV.REWARDACTIVITYGROUPXREF ADD (
  CONSTRAINT XFKREWARDID 
 FOREIGN KEY (REWARDID) 
 REFERENCES INCV.REWARD (REWARDID),
  CONSTRAINT XFK2ACTIVITYGROUPID 
 FOREIGN KEY (ACTIVITYGROUPID) 
 REFERENCES INCV.ACTIVITYGROUP (ACTIVITYGROUPID));

ALTER TABLE INCV.REWARD ADD (
  CONSTRAINT REWARD_FK_PROGRAM 
 FOREIGN KEY (PROGRAMID) 
 REFERENCES INCV.PROGRAM (PROGRAMID));

ALTER TABLE INCV.RELATEDACTIVITYXREF ADD (
  CONSTRAINT PRELACTVTYXREF_FK_ACTVTY 
 FOREIGN KEY (ACTIVITYID) 
 REFERENCES INCV.ACTIVITY (ACTIVITYID),
  CONSTRAINT CRELACTVTYXREF_FK_ACTVTY 
 FOREIGN KEY (RELATEDACTIVITYID) 
 REFERENCES INCV.ACTIVITY (ACTIVITYID),
  CONSTRAINT RELACTVTYREL_FK_MASTERMNEMONIC 
 FOREIGN KEY (RELATIONTYPEMNEMONIC) 
 REFERENCES INCV.MASTERMNEMONIC (MASTERCODEMNEMONIC));

GRANT SELECT ON INCV.ACTIVITY TO ACTS_APPS;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO ACTS_APPS;

GRANT SELECT ON INCV.ACTIVITYGROUP TO ACTS_APPS;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO ACTS_APPS;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO ACTS_APPS;

GRANT SELECT ON INCV.MASTERGROUP TO ACTS_APPS;

GRANT SELECT ON INCV.MASTERMNEMONIC TO ACTS_APPS;

GRANT SELECT ON INCV.PROGRAM TO ACTS_APPS;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO ACTS_APPS;

GRANT SELECT ON INCV.REWARD TO ACTS_APPS;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO ACTS_APPS;

GRANT SELECT ON INCV.REWARDACTIVITYXREF TO ACTS_APPS;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO ACTS_APPS;

GRANT SELECT ON INCV.ACTIVITY TO ACTS_USER;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO ACTS_USER;

GRANT SELECT ON INCV.ACTIVITYGROUP TO ACTS_USER;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO ACTS_USER;

GRANT SELECT ON INCV.MASTERGROUP TO ACTS_USER;

GRANT SELECT ON INCV.MASTERMNEMONIC TO ACTS_USER;

GRANT SELECT ON INCV.PROGRAM TO ACTS_USER;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO ACTS_USER;

GRANT SELECT ON INCV.REWARD TO ACTS_USER;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO ACTS_USER;

GRANT SELECT ON INCV.REWARDACTIVITYXREF TO ACTS_USER;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO ACTS_USER;

GRANT SELECT ON INCV.INCENTIVEGOALTYPE TO AETINCV_USER;

GRANT SELECT ON INCV.INCENTIVEOVERRIDE TO AETINCV_USER;

GRANT SELECT ON INCV.ACTIVITY TO AKATTULA;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO AKATTULA;

GRANT SELECT ON INCV.ACTIVITY TO AMEAPP;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO AMEAPP;

GRANT SELECT ON INCV.ACTIVITYGROUP TO AMEAPP;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO AMEAPP;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO AMEAPP;

GRANT SELECT ON INCV.MASTERGROUP TO AMEAPP;

GRANT SELECT ON INCV.MASTERMNEMONIC TO AMEAPP;

GRANT SELECT ON INCV.PROGRAM TO AMEAPP;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO AMEAPP;

GRANT SELECT ON INCV.REWARD TO AMEAPP;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO AMEAPP;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO AMEAPP;

GRANT SELECT ON INCV.ACTIVITY TO CEAPP;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO CEAPP;

GRANT SELECT ON INCV.ACTIVITYGROUP TO CEAPP;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO CEAPP;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO CEAPP;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO CEAPP;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO CEAPP;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO CEAPP;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO CEAPP;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO CEAPP;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO CEAPP;

GRANT SELECT ON INCV.MASTERGROUP TO CEAPP;

GRANT SELECT ON INCV.MASTERMNEMONIC TO CEAPP;

GRANT SELECT ON INCV.PROGRAM TO CEAPP;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO CEAPP;

GRANT SELECT ON INCV.REWARD TO CEAPP;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO CEAPP;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO CEAPP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYXREF TO CLMFIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO CLMFIN;

GRANT SELECT ON INCV.PROGRAM TO CM WITH GRANT OPTION;

GRANT SELECT ON INCV.PROGRAM TO CM_APP;

GRANT SELECT ON INCV.PROGRAM TO CM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALTYPE TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEOVERRIDE TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCVSQLSTATEMENT_TMP TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYXREF TO CTLM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO CTLM_USER;

GRANT SELECT ON INCV.ACTIVITY TO DM_USER;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO DM_USER;

GRANT SELECT ON INCV.ACTIVITYGROUP TO DM_USER;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO DM_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO DM_USER;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO DM_USER;

GRANT SELECT ON INCV.MASTERGROUP TO DM_USER;

GRANT SELECT ON INCV.MASTERMNEMONIC TO DM_USER;

GRANT SELECT ON INCV.PROGRAM TO DM_USER;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO DM_USER;

GRANT SELECT ON INCV.REWARD TO DM_USER;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO DM_USER;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO DM_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYXREF TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO ETLADMIN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYXREF TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO FIXER WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO INCV_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEGOALTYPE TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO INCV_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO INCV_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEOVERRIDE TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO INCV_APP;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.REWARDACTIVITYXREF TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO INCV_APP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO INCV_DEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEGOALTYPE TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO INCV_DEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO INCV_DEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEOVERRIDE TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO INCV_DEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.REWARDACTIVITYXREF TO INCV_DEV;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO INCV_DEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.ACTIVITY TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.ACTIVITYDETAIL TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.ACTIVITYGROUP TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.ACTIVITYGROUPACTIVITYXREF TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEATTRIBUTE TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEATTRIBUTEVAL TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEELIGIBILITY TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEGOALTYPE TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEGOALVALUE TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEMESSAGE TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEMESSAGEATTR TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEOVERRIDE TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVERUNDETAIL TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.MASTERGROUP TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.MASTERMNEMONIC TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.PROGRAM TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.RELATEDACTIVITYXREF TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.REWARD TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.REWARDACTIVITYGROUPXREF TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.REWARDACTIVITYXREF TO INCV_DML;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.SUPPLIERPROGRAMASSOC TO INCV_DML;

GRANT SELECT ON INCV.ACTIVITY TO INCV_READ;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO INCV_READ;

GRANT SELECT ON INCV.ACTIVITYGROUP TO INCV_READ;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEGOALTYPE TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVEOVERRIDE TO INCV_READ;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO INCV_READ;

GRANT SELECT ON INCV.INCVSQLSTATEMENT_TMP TO INCV_READ;

GRANT SELECT ON INCV.MASTERGROUP TO INCV_READ;

GRANT SELECT ON INCV.MASTERMNEMONIC TO INCV_READ;

GRANT SELECT ON INCV.PROGRAM TO INCV_READ;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO INCV_READ;

GRANT SELECT ON INCV.REWARD TO INCV_READ;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO INCV_READ;

GRANT SELECT ON INCV.REWARDACTIVITYXREF TO INCV_READ;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO INCV_READ;

GRANT SELECT ON INCV.ACTIVITY TO INCV_USER;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO INCV_USER;

GRANT SELECT ON INCV.ACTIVITYGROUP TO INCV_USER;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO INCV_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO INCV_USER;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO INCV_USER;

GRANT SELECT ON INCV.INCVSQLSTATEMENT_TMP TO INCV_USER;

GRANT SELECT ON INCV.MASTERGROUP TO INCV_USER;

GRANT SELECT ON INCV.MASTERMNEMONIC TO INCV_USER;

GRANT SELECT ON INCV.PROGRAM TO INCV_USER;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO INCV_USER;

GRANT SELECT ON INCV.REWARD TO INCV_USER;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO INCV_USER;

GRANT SELECT ON INCV.REWARDACTIVITYXREF TO INCV_USER;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO INCV_USER;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYXREF TO ODS_DML;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO ODS_DML;

GRANT SELECT ON INCV.ACTIVITY TO ODS_READ;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO ODS_READ;

GRANT SELECT ON INCV.ACTIVITYGROUP TO ODS_READ;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO ODS_READ;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO ODS_READ;

GRANT SELECT ON INCV.INCVSQLSTATEMENT_TMP TO ODS_READ;

GRANT SELECT ON INCV.MASTERGROUP TO ODS_READ;

GRANT SELECT ON INCV.MASTERMNEMONIC TO ODS_READ;

GRANT SELECT ON INCV.PROGRAM TO ODS_READ;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO ODS_READ;

GRANT SELECT ON INCV.REWARD TO ODS_READ;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO ODS_READ;

GRANT SELECT ON INCV.REWARDACTIVITYXREF TO ODS_READ;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO ODS_READ;

GRANT SELECT ON INCV.ACTIVITY TO ODS_USER;

GRANT SELECT ON INCV.ACTIVITYDETAIL TO ODS_USER;

GRANT SELECT ON INCV.ACTIVITYGROUP TO ODS_USER;

GRANT SELECT ON INCV.ACTIVITYGROUPACTIVITYXREF TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTE TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEATTRIBUTEVAL TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEELIGIBILITY TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEGOALTYPE TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEGOALVALUE TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGE TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEATTR TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVEOVERRIDE TO ODS_USER;

GRANT SELECT ON INCV.INCENTIVERUNDETAIL TO ODS_USER;

GRANT SELECT ON INCV.INCVSQLSTATEMENT_TMP TO ODS_USER;

GRANT SELECT ON INCV.MASTERGROUP TO ODS_USER;

GRANT SELECT ON INCV.MASTERMNEMONIC TO ODS_USER;

GRANT SELECT ON INCV.PROGRAM TO ODS_USER;

GRANT SELECT ON INCV.RELATEDACTIVITYXREF TO ODS_USER;

GRANT SELECT ON INCV.REWARD TO ODS_USER;

GRANT SELECT ON INCV.REWARDACTIVITYGROUPXREF TO ODS_USER;

GRANT SELECT ON INCV.REWARDACTIVITYXREF TO ODS_USER;

GRANT SELECT ON INCV.SUPPLIERPROGRAMASSOC TO ODS_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITY TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYDETAIL TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUP TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.ACTIVITYGROUPACTIVITYXREF TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTE TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEATTRIBUTEVAL TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEELIGIBILITY TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALTYPE TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEGOALVALUE TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGE TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEATTR TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEMESSAGEDEFAULTATTR TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVEOVERRIDE TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCENTIVERUNDETAIL TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.INCVSQLSTATEMENT_TMP TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERGROUP TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.MASTERMNEMONIC TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.PROGRAM TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.RELATEDACTIVITYXREF TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARD TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYGROUPXREF TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.REWARDACTIVITYXREF TO PURGE_USER;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INCV.SUPPLIERPROGRAMASSOC TO PURGE_USER;


/* HD/AH 2019.05.22 */
CREATE TABLE INCV.MEMBERPROGRAMLASTRUN
(
    MEMBERACTIVITYLASTRUNSKEY  NUMBER             NOT NULL,
    MEMBERID                   NUMBER             NOT NULL,
    PROGRAMID                  NUMBER,
    INCENTIVERUNID             NUMBER,
    VOIDFLG                    VARCHAR2(2 BYTE)   NOT NULL,
    INSERTEDDT                 TIMESTAMP(6)       NOT NULL,
    INSERTEDBY                 VARCHAR2(30 BYTE)  NOT NULL,
    UPDATEDDT                  TIMESTAMP(6),
    UPDATEDBY                  VARCHAR2(30 BYTE),
    MASTERSUPPLIERID           NUMBER             NOT NULL,
    YEARQTR                    NUMBER             NOT NULL
);


CREATE TABLE INCV.MEMBERREDEMPTION
(
    MEMBERREDEMPTIONSKEY   NUMBER                 NOT NULL,
    PROGRAMID              NUMBER                 NOT NULL,
    REWARDID               NUMBER                 NOT NULL,
    MEMBERID               NUMBER                 NOT NULL,
    MEMBERPLANID           NUMBER                 NOT NULL,
    REDEMPTIONVAL          NUMBER                 NOT NULL,
    REDEMPTIONDT           TIMESTAMP(6)           NOT NULL,
    REDEMPTIONDESC         VARCHAR2(255 BYTE)     NOT NULL,
    REDEMTIONTYPEMNEMONIC  VARCHAR2(50 BYTE)      NOT NULL,
    VOIDFLG                VARCHAR2(2 BYTE)       NOT NULL,
    INSERTEDDT             TIMESTAMP(6)           DEFAULT systimestamp
                                                  NOT NULL,
    INSERTEDBY             VARCHAR2(30 BYTE)      DEFAULT USER
                                                  NOT NULL,
    UPDATEDDT              TIMESTAMP(6)           DEFAULT systimestamp
                                                  NOT NULL,
    UPDATEDBY              VARCHAR2(30 BYTE)      DEFAULT USER
                                                  NOT NULL,
    MASTERSUPPLIERID       NUMBER                 NOT NULL,
    YEARQTR                NUMBER                 NOT NULL
);


CREATE TABLE INCV.MEMBERACTIVITYOCCURRENCE
(
    RUNDT                           DATE          NOT NULL,
    MEMBERACTIVITYOCCURRENCESKEY    NUMBER        NOT NULL,
    AHMSUPPLIERID                   VARCHAR2(50 BYTE) NOT NULL,
    MEMBERID                        NUMBER        NOT NULL,
    MEMBERPLANID                    NUMBER        NOT NULL,
    INCENTIVERUNID                  NUMBER        NOT NULL,
    PROGRAMID                       NUMBER,
    REWARDID                        NUMBER,
    ACTIVITYID                      NUMBER        NOT NULL,
    REWARDSTATUSMNEMONIC            VARCHAR2(50 BYTE) NOT NULL,
    RECORDSTATUSMNEMONIC            VARCHAR2(50 BYTE) NOT NULL,
    ACTIVITYSTATUSMNEMONIC          VARCHAR2(50 BYTE) NOT NULL,
    ACTIVITYOCCURSTATUSMNEMONIC     VARCHAR2(50 BYTE),
    Z_EARNEDREWARDVAL               NUMBER,
    ACTIVITYOCCURRENCEDT            TIMESTAMP(6),
    ISOPENIND                       VARCHAR2(1 BYTE) NOT NULL,
    ISPRESENTIND                    VARCHAR2(1 BYTE) NOT NULL,
    ISAPPLICABLEIND                 VARCHAR2(1 BYTE) NOT NULL,
    PARAM1                          VARCHAR2(255 BYTE),
    PARAM2                          VARCHAR2(255 BYTE),
    PARAM3                          VARCHAR2(255 BYTE),
    VOIDFLG                         VARCHAR2(2 BYTE) NOT NULL,
    INSERTEDDT                      TIMESTAMP(6)  NOT NULL,
    INSERTEDBY                      VARCHAR2(30 BYTE) NOT NULL,
    UPDATEDDT                       TIMESTAMP(6),
    UPDATEDBY                       VARCHAR2(30 BYTE),
    Z_EARNEDOCCURRENCEVAL           NUMBER        DEFAULT 0,
    Z_EARNEDACTIVITYVAL             NUMBER        DEFAULT 0,
    REWARDCOMPLETIONDATE            DATE,
    ACTIVITYCOMPLETIONDT            DATE,
    OVERRIDDENYNIND                 VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
    MBRINCENTIVESTATUSOVERRIDESKEY  NUMBER,
    INVALIDIND                      VARCHAR2(1 BYTE) DEFAULT 'N',
    ACTIVITYSTARTDT                 TIMESTAMP(6)  NOT NULL,
    ACTIVITYENDDT                   TIMESTAMP(6)  NOT NULL,
    REWARDSTARTDT                   TIMESTAMP(6)  NOT NULL,
    REWARDENDDT                     TIMESTAMP(6)  NOT NULL,
    Z_MAXREWARDVAL                  NUMBER,
    Z_REDEEMEDREWARDVAL             NUMBER,
    Z_BALANCEREWARDVAL              NUMBER,
    MASTERSUPPLIERID                NUMBER        NOT NULL,
    YEARQTR                         NUMBER        NOT NULL
);

CREATE TABLE INCV.MEMBERTIERINFO
(
    MEMBERTIERINFOSKEY  NUMBER                    NOT NULL,
    MEMBERPLANID        NUMBER                    NOT NULL,
    MEMBERID            NUMBER                    NOT NULL,
    REWARDID            NUMBER,
    MEMBERTIERMNEMONIC  VARCHAR2(50 BYTE)         NOT NULL,
    GOALTYPEMNEMONIC    VARCHAR2(50 BYTE)         NOT NULL,
    EFFSTARTDT          TIMESTAMP(6)              NOT NULL,
    EFFENDDT            TIMESTAMP(6),
    VOIDFLG             CHAR(2 BYTE)              NOT NULL,
    INSERTEDDT          TIMESTAMP(6)              DEFAULT systimestamp
                                                  NOT NULL,
    INSERTEDBY          VARCHAR2(30 BYTE)         DEFAULT USER
                                                  NOT NULL,
    UPDATEDDT           TIMESTAMP(6)              DEFAULT systimestamp,
    UPDATEDBY           VARCHAR2(30 BYTE)         DEFAULT USER
);

-- EXIT;