-- SET ECHO ON

--
-- CAREENGINERUNMEMBERACTION  (Table) 
--
CREATE TABLE CSID.CAREENGINERUNMEMBERACTION
(
  CAREENGINERUNMEMBERACTIONID     NUMBER        NOT NULL,
  PRODUCTMNEMONICCD               VARCHAR2(50 BYTE)     NULL,
  MEMBERRECOMMENDRUNID            NUMBER            NULL,
  OVERALLSCORENBR                 NUMBER            NULL,
  INSERTUPDATECD                  VARCHAR2(12 BYTE)     NULL,
  RECOMMENDFLG                    CHAR(1 BYTE)      NULL,
  INSERTEDBY                      VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  RECORDINSERTDT                  TIMESTAMP(6)  DEFAULT SYSTIMESTAMP          NOT NULL,
  RECORDUPDTDT                    TIMESTAMP(6)  DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDTDBY                         VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  CAREENGINERUNTRACKINGIDTYPECD   VARCHAR2(12 BYTE)     NULL,
  CAREENGINERUNACTIONTRACKINGID   NUMBER            NULL,
  PROGRAMREFERRALINTENSITYCD      VARCHAR2(12 BYTE)     NULL,
  SUBPRODUCTMNEMONICCD            VARCHAR2(50 BYTE)     NULL,
  VBFINSTRUCTIONCD                VARCHAR2(4 BYTE)     NULL,
  PARTITIONID                     NUMBER(38)        NULL,
  PROGRAMIDENTIFICATIONEPISODEID  NUMBER            NULL,
  IMPACTABLESCORENBR              NUMBER            NULL,
  MASTERSUPPLIERID                NUMBER        NOT NULL,
  YEARQTR                         NUMBER        NOT NULL
);


--
-- MEMBERHEALTHSTATE  (Table) 
--
CREATE TABLE CSID.MEMBERHEALTHSTATE
(
  MEMBERHEALTHSTATESKEY         NUMBER          NOT NULL,
  EPISODEID                     NUMBER          NOT NULL,
  VERSIONNBR                    NUMBER          NOT NULL,
  STATETYPECD                   VARCHAR2(4 BYTE) NOT NULL,
  STATECOMPONENTID              NUMBER              NULL,
  MEMBERID                      NUMBER          NOT NULL,
  HEALTHSTATESTATUSCD           VARCHAR2(12 BYTE)     NULL,
  HEALTHSTATESTATUSCHANGERSNCD  VARCHAR2(12 BYTE)     NULL,
  HEALTHSTATESTATUSCHANGEDT     DATE                NULL,
  HEALTHSTATECHANGEDT           DATE            NOT NULL,
  SEVERITYLEVEL                 VARCHAR2(12 BYTE)     NULL,
  COMPLETIONFLG                 CHAR(1 BYTE)    NOT NULL,
  CLINICALREVIEWSTATUSCD        VARCHAR2(12 BYTE)     NULL,
  CLINICALREVIEWSTATUSDT        DATE                NULL,
  LASTEVALUATIONDT              DATE                NULL,
  VOIDFLG                       VARCHAR2(2 BYTE)     NULL,
  INSERTEDBY                    VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  INSERTEDDT                    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDATEDBY                     VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  UPDATEDDT                     TIMESTAMP(6)    DEFAULT SYSTIMESTAMP          NOT NULL,
  SEVERITYSCORE                 NUMBER              NULL,
  MASTERSUPPLIERID              NUMBER          NOT NULL,
  YEARQTR                       NUMBER          NOT NULL,
  PDCSCOREPERC                  NUMBER              NULL
);


--
-- MEMBERHEALTHSTATEFEEDBACKXREF  (Table) 
--
CREATE TABLE CSID.MEMBERHEALTHSTATEFEEDBACKXREF
(
  MEMBERHEALTHSTATEFEEDBACKSKEY  NUMBER         NOT NULL,
  CLINICALOUTPUTTYPECD           VARCHAR2(4 BYTE) NOT NULL,
  CLINICALOUTPUTTRACKINGID       NUMBER         NOT NULL,
  INSERTEDBY                     VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  INSERTEDDT                     TIMESTAMP(6)   DEFAULT systimestamp          NOT NULL,
  UPDATEDBY                      VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  UPDATEDDT                      TIMESTAMP(6)   DEFAULT systimestamp          NOT NULL,
  MEMBERHEALTHSTATESKEY          NUMBER             NULL
);


--
-- MEMBERRECOMMENDPRODUCTLASTRUN  (Table) 
--
CREATE TABLE CSID.MEMBERRECOMMENDPRODUCTLASTRUN
(
  MEMBERID                     NUMBER           NOT NULL,
  BUSINESSSUPPLIERID           NUMBER           NOT NULL,
  PRODUCTMNEMONICCD            VARCHAR2(50 BYTE) NOT NULL,
  CAREENGINERUNMEMBERACTIONID  NUMBER               NULL,
  RUNDT                        TIMESTAMP(6)     NOT NULL,
  INSERTEDDT                   TIMESTAMP(6)     DEFAULT SYSTIMESTAMP          NOT NULL,
  INSERTEDBY                   VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  UPDATEDDT                    TIMESTAMP(6)     DEFAULT SYSTIMESTAMP          NOT NULL,
  UPDATEDBY                    VARCHAR2(30 BYTE) DEFAULT USER NOT NULL,
  EXECUTIONMODECD              VARCHAR2(10 BYTE)     NULL,
  MASTERSUPPLIERID             NUMBER           NOT NULL,
  YEARQTR                      NUMBER           NOT NULL,
  PERSONMASTERSUPPLIERID       NUMBER               NULL
);


--
-- MBRRECPRODLASTRUN_FK_CAREEGACT  (Index) 
--
--  Dependencies: 
--   MEMBERRECOMMENDPRODUCTLASTRUN (Table)
--
CREATE INDEX CSID.MBRRECPRODLASTRUN_FK_CAREEGACT ON CSID.MEMBERRECOMMENDPRODUCTLASTRUN
(CAREENGINERUNMEMBERACTIONID);

--
-- MBRRECPRODLASTRUN_FK_OPRPROD  (Index) 
--
--  Dependencies: 
--   MEMBERRECOMMENDPRODUCTLASTRUN (Table)
--
CREATE INDEX CSID.MBRRECPRODLASTRUN_FK_OPRPROD ON CSID.MEMBERRECOMMENDPRODUCTLASTRUN
(PRODUCTMNEMONICCD);

--
-- X1FK1CAREENGINERUNMEMBERACTION  (Index) 
--
--  Dependencies: 
--   CAREENGINERUNMEMBERACTION (Table)
--
CREATE INDEX CSID.X1FK1CAREENGINERUNMEMBERACTION ON CSID.CAREENGINERUNMEMBERACTION
(MEMBERRECOMMENDRUNID);

--
-- X1I1CAREENGINERUNMEMBERACTION  (Index) 
--
--  Dependencies: 
--   CAREENGINERUNMEMBERACTION (Table)
--
CREATE INDEX CSID.X1I1CAREENGINERUNMEMBERACTION ON CSID.CAREENGINERUNMEMBERACTION
(MEMBERRECOMMENDRUNID, PRODUCTMNEMONICCD);

--
-- XIE1MEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE INDEX CSID.XIE1MEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(MEMBERID, STATECOMPONENTID, STATETYPECD);

--
-- XIE1MEMBERHEALTHSTATEFEEDBACKX  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATEFEEDBACKXREF (Table)
--
CREATE INDEX CSID.XIE1MEMBERHEALTHSTATEFEEDBACKX ON CSID.MEMBERHEALTHSTATEFEEDBACKXREF
(CLINICALOUTPUTTRACKINGID, CLINICALOUTPUTTYPECD);

--
-- XIE2MBRRECOMPRODLAST  (Index) 
--
--  Dependencies: 
--   MEMBERRECOMMENDPRODUCTLASTRUN (Table)
--
CREATE INDEX CSID.XIE2MBRRECOMPRODLAST ON CSID.MEMBERRECOMMENDPRODUCTLASTRUN
(YEARQTR);

--
-- XIE2MEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE INDEX CSID.XIE2MEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(HEALTHSTATECHANGEDT);

--
-- XIE3MEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE INDEX CSID.XIE3MEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(CLINICALREVIEWSTATUSDT, CLINICALREVIEWSTATUSCD);

--
-- XIE4MEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE INDEX CSID.XIE4MEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(LASTEVALUATIONDT, CLINICALREVIEWSTATUSCD);

--
-- XIE5MEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE INDEX CSID.XIE5MEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(YEARQTR);

--
-- XIE6MEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE INDEX CSID.XIE6MEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(MASTERSUPPLIERID, MEMBERID);

--
-- XPKCERMA  (Index) 
--
--  Dependencies: 
--   CAREENGINERUNMEMBERACTION (Table)
--
CREATE UNIQUE INDEX CSID.XPKCERMA ON CSID.CAREENGINERUNMEMBERACTION
(CAREENGINERUNMEMBERACTIONID, MASTERSUPPLIERID, YEARQTR);

--
-- XPKMEMBERHEALTHSTATE  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATE (Table)
--
CREATE UNIQUE INDEX CSID.XPKMEMBERHEALTHSTATE ON CSID.MEMBERHEALTHSTATE
(MEMBERHEALTHSTATESKEY, MASTERSUPPLIERID);

--
-- XPKMEMBERRECOMMENDPRODLASTRUN  (Index) 
--
--  Dependencies: 
--   MEMBERRECOMMENDPRODUCTLASTRUN (Table)
--
CREATE UNIQUE INDEX CSID.XPKMEMBERRECOMMENDPRODLASTRUN ON CSID.MEMBERRECOMMENDPRODUCTLASTRUN
(MEMBERID, BUSINESSSUPPLIERID, PRODUCTMNEMONICCD, MASTERSUPPLIERID);

--
-- XPKMEMHEALTHSTATEFEEDBACKXREF  (Index) 
--
--  Dependencies: 
--   MEMBERHEALTHSTATEFEEDBACKXREF (Table)
--
CREATE UNIQUE INDEX CSID.XPKMEMHEALTHSTATEFEEDBACKXREF ON CSID.MEMBERHEALTHSTATEFEEDBACKXREF
(MEMBERHEALTHSTATEFEEDBACKSKEY, CLINICALOUTPUTTYPECD, CLINICALOUTPUTTRACKINGID);

-- 
-- Non Foreign Key Constraints for Table CAREENGINERUNMEMBERACTION 
-- 
ALTER TABLE CSID.CAREENGINERUNMEMBERACTION ADD (
  CONSTRAINT CEMEMBERACTIONVBFINSTRUCTIONCD
  CHECK (VBFInstructionCd IN ('INCV', 'DISC', 'NONE'))
  ENABLE VALIDATE);

ALTER TABLE CSID.CAREENGINERUNMEMBERACTION ADD (
  CONSTRAINT XPKCERMA
  PRIMARY KEY
  (CAREENGINERUNMEMBERACTIONID, MASTERSUPPLIERID, YEARQTR)
  USING INDEX CSID.XPKCERMA
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MEMBERHEALTHSTATE 
-- 
ALTER TABLE CSID.MEMBERHEALTHSTATE ADD (
  CONSTRAINT MEMBERHEALTHSTATE_C01
  CHECK (STATETYPECD IN ('MK', 'ME'))
  ENABLE VALIDATE);

ALTER TABLE CSID.MEMBERHEALTHSTATE ADD (
  CONSTRAINT MEMBERHEALTHSTATE_C02
  CHECK (COMPLETIONFLG IN ('Y', 'N'))
  ENABLE VALIDATE);

ALTER TABLE CSID.MEMBERHEALTHSTATE ADD (
  CONSTRAINT XPKMEMBERHEALTHSTATE
  PRIMARY KEY
  (MEMBERHEALTHSTATESKEY, MASTERSUPPLIERID)
  USING INDEX CSID.XPKMEMBERHEALTHSTATE
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MEMBERHEALTHSTATEFEEDBACKXREF 
-- 
ALTER TABLE CSID.MEMBERHEALTHSTATEFEEDBACKXREF ADD (
  CONSTRAINT MEMHEALTHSTATEFEEDBACKXREF_C01
  CHECK (Clinicaloutputtypecd IN ('MRS', 'MHS', 'COM'))
  ENABLE VALIDATE);

ALTER TABLE CSID.MEMBERHEALTHSTATEFEEDBACKXREF ADD (
  PRIMARY KEY
  (MEMBERHEALTHSTATEFEEDBACKSKEY, CLINICALOUTPUTTYPECD, CLINICALOUTPUTTRACKINGID)
  USING INDEX CSID.XPKMEMHEALTHSTATEFEEDBACKXREF
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MEMBERRECOMMENDPRODUCTLASTRUN 
-- 
ALTER TABLE CSID.MEMBERRECOMMENDPRODUCTLASTRUN ADD (
  CONSTRAINT XPKMEMBERRECOMMENDPRODLASTRUN
  PRIMARY KEY
  (MEMBERID, BUSINESSSUPPLIERID, PRODUCTMNEMONICCD, MASTERSUPPLIERID)
  USING INDEX CSID.XPKMEMBERRECOMMENDPRODLASTRUN
  ENABLE VALIDATE);

-- EXIT;