/* added by HJD */

SET ECHO ON

ALTER USER system QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO system;

CREATE USER INCV IDENTIFIED BY INCV;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO INCV;
GRANT UNLIMITED TABLESPACE TO INCV;

CREATE USER INCV_APP IDENTIFIED BY INCV_APP;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO INCV_APP;
GRANT UNLIMITED TABLESPACE TO INCV_APP;

CREATE USER INCV_DEV IDENTIFIED BY INCV_DEV;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO INCV_DEV;
GRANT UNLIMITED TABLESPACE TO INCV_DEV;

CREATE USER INCV_DML IDENTIFIED BY INCV_DML;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO INCV_DML;
GRANT UNLIMITED TABLESPACE TO INCV_DML;

CREATE USER INCV_READ IDENTIFIED BY INCV_READ;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO INCV_READ;
GRANT UNLIMITED TABLESPACE TO INCV_READ;

CREATE USER INCV_USER IDENTIFIED BY INCV_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO INCV_USER;
GRANT UNLIMITED TABLESPACE TO INCV_USER;

CREATE USER ODS IDENTIFIED BY ODS;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ODS;
GRANT UNLIMITED TABLESPACE TO ODS;

CREATE USER ODS_DML IDENTIFIED BY ODS_DML;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ODS_DML;
GRANT UNLIMITED TABLESPACE TO ODS_DML;

CREATE USER ODS_READ IDENTIFIED BY ODS_READ;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ODS_READ;
GRANT UNLIMITED TABLESPACE TO ODS_READ;

CREATE USER ODS_USER IDENTIFIED BY ODS_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ODS_USER;
GRANT UNLIMITED TABLESPACE TO ODS_USER;

CREATE USER ACTS_APPS IDENTIFIED BY ACTS_APPS;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ACTS_APPS;
GRANT UNLIMITED TABLESPACE TO ACTS_APPS;

CREATE USER ACTS_USER IDENTIFIED BY ACTS_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ACTS_USER;
GRANT UNLIMITED TABLESPACE TO ACTS_USER;

CREATE USER AETINCV_USER IDENTIFIED BY AETINCV_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO AETINCV_USER;
GRANT UNLIMITED TABLESPACE TO AETINCV_USER;

CREATE USER AKATTULA IDENTIFIED BY AKATTULA;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO AKATTULA;
GRANT UNLIMITED TABLESPACE TO AKATTULA;

CREATE USER AMEAPP IDENTIFIED BY AMEAPP;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO AMEAPP;
GRANT UNLIMITED TABLESPACE TO AMEAPP;

CREATE USER CEAPP IDENTIFIED BY CEAPP;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CEAPP;
GRANT UNLIMITED TABLESPACE TO CEAPP;

CREATE USER CLMFIN IDENTIFIED BY CLMFIN;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CLMFIN;
GRANT UNLIMITED TABLESPACE TO CLMFIN;

CREATE USER CM IDENTIFIED BY CM;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CM;
GRANT UNLIMITED TABLESPACE TO CM;

CREATE USER CM_APP IDENTIFIED BY CM_APP;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CM_APP;
GRANT UNLIMITED TABLESPACE TO CM_APP;

CREATE USER CM_USER IDENTIFIED BY CM_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CM_USER;
GRANT UNLIMITED TABLESPACE TO CM_USER;

CREATE USER CTLM_USER IDENTIFIED BY CTLM_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CTLM_USER;
GRANT UNLIMITED TABLESPACE TO CTLM_USER;

CREATE USER DM_USER IDENTIFIED BY DM_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO DM_USER;
GRANT UNLIMITED TABLESPACE TO DM_USER;

CREATE USER ETLADMIN IDENTIFIED BY ETLADMIN;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ETLADMIN;
GRANT UNLIMITED TABLESPACE TO ETLADMIN;

CREATE USER FIXER IDENTIFIED BY FIXER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO FIXER;
GRANT UNLIMITED TABLESPACE TO FIXER;

CREATE USER PURGE_USER IDENTIFIED BY PURGE_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO PURGE_USER;
GRANT UNLIMITED TABLESPACE TO PURGE_USER;

CREATE USER ADHAS IDENTIFIED BY ADHAS;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO ADHAS;
GRANT UNLIMITED TABLESPACE TO ADHAS;

CREATE USER MKONDADI IDENTIFIED BY MKONDADI;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO MKONDADI;
GRANT UNLIMITED TABLESPACE TO MKONDADI;

CREATE USER SSELVAKUMAR IDENTIFIED BY SSELVAKUMAR;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO SSELVAKUMAR;
GRANT UNLIMITED TABLESPACE TO SSELVAKUMAR;

CREATE USER TPANDE IDENTIFIED BY TPANDE;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO TPANDE;
GRANT UNLIMITED TABLESPACE TO TPANDE;

CREATE USER CSID IDENTIFIED BY CSID;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CSID;
GRANT UNLIMITED TABLESPACE TO CSID;

CREATE USER CSID_DML IDENTIFIED BY CSID_DML;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO CSID_DML;
GRANT UNLIMITED TABLESPACE TO CSID_DML;

CREATE USER COMMENG IDENTIFIED BY COMMENG;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO COMMENG;
GRANT UNLIMITED TABLESPACE TO COMMENG;

CREATE USER COMMENG_USER IDENTIFIED BY COMMENG_USER;
GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY INDEX, CREATE ANY SEQUENCE, CREATE ANY VIEW, RESOURCE, DBA TO COMMENG_USER;
GRANT UNLIMITED TABLESPACE TO COMMENG_USER;

EXIT;