SET ECHO ON

GRANT SELECT ON MEMBERHEALTHSTATEFEEDBACKXREF TO INCV;
GRANT DELETE ON MEMBERHEALTHSTATEFEEDBACKXREF TO INCV;
GRANT INSERT ON MEMBERHEALTHSTATEFEEDBACKXREF TO INCV;
GRANT UPDATE ON MEMBERHEALTHSTATEFEEDBACKXREF TO INCV;
GRANT SELECT ON CAREENGINERUNMEMBERACTION TO INCV WITH GRANT OPTION;
GRANT DELETE ON CAREENGINERUNMEMBERACTION TO INCV;
GRANT INSERT ON CAREENGINERUNMEMBERACTION TO INCV;
GRANT UPDATE ON CAREENGINERUNMEMBERACTION TO INCV;
GRANT SELECT ON MEMBERRECOMMENDPRODUCTLASTRUN TO INCV WITH GRANT OPTION;
GRANT DELETE ON MEMBERRECOMMENDPRODUCTLASTRUN TO INCV;
GRANT INSERT ON MEMBERRECOMMENDPRODUCTLASTRUN TO INCV;
GRANT UPDATE ON MEMBERRECOMMENDPRODUCTLASTRUN TO INCV;
GRANT SELECT ON MEMBERHEALTHSTATE TO INCV;
GRANT DELETE ON MEMBERHEALTHSTATE TO INCV;
GRANT INSERT ON MEMBERHEALTHSTATE TO INCV;
GRANT UPDATE ON MEMBERHEALTHSTATE TO INCV;

GRANT SELECT ON MEMBERHEALTHSTATEFEEDBACKXREF TO ODS WITH GRANT OPTION;
GRANT DELETE ON MEMBERHEALTHSTATEFEEDBACKXREF TO ODS;
GRANT INSERT ON MEMBERHEALTHSTATEFEEDBACKXREF TO ODS;
GRANT UPDATE ON MEMBERHEALTHSTATEFEEDBACKXREF TO ODS;
GRANT DELETE ON CAREENGINERUNMEMBERACTION TO ODS;
GRANT INSERT ON CAREENGINERUNMEMBERACTION TO ODS;
GRANT SELECT ON CAREENGINERUNMEMBERACTION TO ODS;
GRANT UPDATE ON CAREENGINERUNMEMBERACTION TO ODS;
GRANT DELETE ON MEMBERRECOMMENDPRODUCTLASTRUN TO ODS;
GRANT INSERT ON MEMBERRECOMMENDPRODUCTLASTRUN TO ODS;
GRANT SELECT ON MEMBERRECOMMENDPRODUCTLASTRUN TO ODS;
GRANT UPDATE ON MEMBERRECOMMENDPRODUCTLASTRUN TO ODS;
GRANT DELETE ON MEMBERHEALTHSTATE TO ODS;
GRANT INSERT ON MEMBERHEALTHSTATE TO ODS;
GRANT SELECT ON MEMBERHEALTHSTATE TO ODS WITH GRANT OPTION;
GRANT UPDATE ON MEMBERHEALTHSTATE TO ODS;

EXIT;